import { STATUS } from "@/enum";
export type Project = {
  id: string;
  name: string;
  project_manager: string;
  status: STATUS;
  last_updated: string;
  resources: string[];
  start_date: string;
  end_date: string;
  estimated_cost: number;
};

export const projects: Project[] = [
  {
    id: "1",
    name: "Nice web app",
    project_manager: "James Turner",
    status: STATUS.ON_TRACK,
    last_updated: "31 Oct 2024, 06:00 PM",
    resources: [
      "Research & Development",
      "Marketing",
      "Backend Development",
      "Frontend Development",
      "Data Analysis",
      "Project Management",
    ],
    start_date: "04 Jul 2024",
    end_date: "20 Jan 2024",
    estimated_cost: 6641,
  },
  {
    id: "2",
    name: "Begin web app",
    project_manager: "Kaitlyn Williams",
    status: STATUS.ON_HOLD,
    last_updated: "13 Jun 2024, 08:18 AM",
    resources: ["UX/UI Design", "Data Analysis", "Frontend Development"],
    start_date: "31 Jan 2024",
    end_date: "02 Jan 2024",
    estimated_cost: 19906,
  },
  {
    id: "3",
    name: "Important web app",
    project_manager: "Emily Blair",
    status: STATUS.ON_TRACK,
    last_updated: "27 Nov 2024, 09:56 AM",
    resources: [
      "Frontend Development",
      "QA",
      "Research & Development",
      "Infrastructure",
      "Project Management",
    ],
    start_date: "04 Aug 2024",
    end_date: "08 Jun 2024",
    estimated_cost: 6115,
  },
  {
    id: "4",
    name: "Federal web app",
    project_manager: "Anthony Saunders",
    status: STATUS.RISK,
    last_updated: "04 Nov 2024, 12:28 AM",
    resources: [
      "Testing",
      "Project Management",
      "Backend Development",
      "Frontend Development",
      "Infrastructure",
      "Marketing",
    ],
    start_date: "01 Jun 2024",
    end_date: "14 Feb 2024",
    estimated_cost: 17790,
  },
  {
    id: "5",
    name: "Mrs web app",
    project_manager: "Patrick Stuart",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "24 Nov 2024, 09:05 AM",
    resources: [
      "Data Analysis",
      "Project Management",
      "UX/UI Design",
      "Infrastructure",
    ],
    start_date: "19 May 2024",
    end_date: "19 Feb 2024",
    estimated_cost: 10015,
  },
  {
    id: "6",
    name: "Building web app",
    project_manager: "John West",
    status: STATUS.ON_TRACK,
    last_updated: "12 Mar 2024, 05:52 AM",
    resources: ["Data Analysis", "QA", "Infrastructure"],
    start_date: "09 Mar 2024",
    end_date: "09 Jun 2024",
    estimated_cost: 12500,
  },
  {
    id: "7",
    name: "Creative web app",
    project_manager: "Sophia Harris",
    status: STATUS.ON_HOLD,
    last_updated: "20 Nov 2024, 04:27 PM",
    resources: ["UX/UI Design", "Project Management", "Data Analysis"],
    start_date: "14 May 2024",
    end_date: "18 Oct 2024",
    estimated_cost: 10908,
  },
  {
    id: "8",
    name: "Future web app",
    project_manager: "William Wright",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "03 Nov 2024, 10:32 AM",
    resources: [
      "Backend Development",
      "Frontend Development",
      "Research & Development",
      "Testing",
    ],
    start_date: "25 Apr 2024",
    end_date: "05 Dec 2024",
    estimated_cost: 13472,
  },
  {
    id: "9",
    name: "Velocity web app",
    project_manager: "David Johnson",
    status: STATUS.ON_TRACK,
    last_updated: "17 Oct 2024, 02:18 PM",
    resources: ["QA", "Project Management", "Frontend Development"],
    start_date: "02 Mar 2024",
    end_date: "13 Jul 2024",
    estimated_cost: 8880,
  },
  {
    id: "10",
    name: "Everest web app",
    project_manager: "Isabella Green",
    status: STATUS.RISK,
    last_updated: "08 Aug 2024, 09:47 PM",
    resources: [
      "Marketing",
      "Infrastructure",
      "Backend Development",
      "Testing",
    ],
    start_date: "12 Feb 2024",
    end_date: "20 May 2024",
    estimated_cost: 17990,
  },
  {
    id: "11",
    name: "Super web app",
    project_manager: "Paul Foster",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "12 Jun 2024, 10:15 AM",
    resources: [
      "QA",
      "Backend Development",
      "Research & Development",
      "Marketing",
      "Frontend Development",
      "Infrastructure",
    ],
    start_date: "13 Aug 2024",
    end_date: "17 Jan 2024",
    estimated_cost: 8423,
  },
  {
    id: "12",
    name: "Amount web app",
    project_manager: "Olivia Hubbard",
    status: STATUS.ON_HOLD,
    last_updated: "06 Oct 2024, 12:45 AM",
    resources: [
      "UX/UI Design",
      "Testing",
      "Data Analysis",
      "Research & Development",
      "Backend Development",
    ],
    start_date: "27 Oct 2024",
    end_date: "28 Oct 2024",
    estimated_cost: 6053,
  },
  {
    id: "13",
    name: "Single web app",
    project_manager: "Gordon Vasquez",
    status: STATUS.RISK,
    last_updated: "10 Jul 2024, 12:37 AM",
    resources: [
      "UX/UI Design",
      "Research & Development",
      "Backend Development",
    ],
    start_date: "16 Oct 2024",
    end_date: "17 Sep 2024",
    estimated_cost: 7271,
  },
  {
    id: "14",
    name: "Tree web app",
    project_manager: "Scott Henry",
    status: STATUS.ON_HOLD,
    last_updated: "28 Nov 2024, 08:34 AM",
    resources: [
      "Marketing",
      "Research & Development",
      "Frontend Development",
      "Project Management",
    ],
    start_date: "17 May 2024",
    end_date: "16 Nov 2024",
    estimated_cost: 5063,
  },
  {
    id: "15",
    name: "Production web app",
    project_manager: "Daniel Fleming",
    status: STATUS.ON_TRACK,
    last_updated: "02 Jan 2024, 01:52 AM",
    resources: [
      "Marketing",
      "Project Management",
      "Research & Development",
      "Testing",
      "UX/UI Design",
    ],
    start_date: "12 Jun 2024",
    end_date: "03 Sep 2024",
    estimated_cost: 13639,
  },
  {
    id: "16",
    name: "Mother web app",
    project_manager: "Cody Paul",
    status: STATUS.ON_HOLD,
    last_updated: "04 May 2024, 10:30 PM",
    resources: [
      "Marketing",
      "Backend Development",
      "Testing",
      "Research & Development",
      "UX/UI Design",
    ],
    start_date: "07 Oct 2024",
    end_date: "25 Mar 2024",
    estimated_cost: 16905,
  },
  {
    id: "17",
    name: "Prime web app",
    project_manager: "Ethan Moore",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "02 Nov 2024, 08:12 AM",
    resources: [
      "Frontend Development",
      "Backend Development",
      "QA",
      "Project Management",
      "Research & Development",
    ],
    start_date: "20 Jul 2024",
    end_date: "25 Nov 2024",
    estimated_cost: 11234,
  },
  {
    id: "18",
    name: "Tech web app",
    project_manager: "Madeline Davis",
    status: STATUS.RISK,
    last_updated: "15 Aug 2024, 06:23 AM",
    resources: [
      "Marketing",
      "Backend Development",
      "Data Analysis",
      "Research & Development",
    ],
    start_date: "01 Apr 2024",
    end_date: "03 Jul 2024",
    estimated_cost: 9463,
  },
  {
    id: "19",
    name: "Bold web app",
    project_manager: "Lucas Martin",
    status: STATUS.ON_TRACK,
    last_updated: "07 Sep 2024, 02:57 PM",
    resources: ["Frontend Development", "Project Management", "QA"],
    start_date: "11 Dec 2023",
    end_date: "15 Jun 2024",
    estimated_cost: 13021,
  },
  {
    id: "20",
    name: "Space web app",
    project_manager: "Ava Wilson",
    status: STATUS.ON_HOLD,
    last_updated: "18 Apr 2024, 09:18 AM",
    resources: [
      "Backend Development",
      "Research & Development",
      "Marketing",
      "UX/UI Design",
    ],
    start_date: "17 Jan 2024",
    end_date: "30 Aug 2024",
    estimated_cost: 10891,
  },
  {
    id: "21",
    name: "Galaxy web app",
    project_manager: "Benjamin Thomas",
    status: STATUS.ON_TRACK,
    last_updated: "23 Nov 2024, 11:30 AM",
    resources: [
      "Infrastructure",
      "Frontend Development",
      "QA",
      "Project Management",
      "Research & Development",
    ],
    start_date: "22 Jun 2024",
    end_date: "14 Dec 2024",
    estimated_cost: 9250,
  },
  {
    id: "22",
    name: "Dragon web app",
    project_manager: "Olivia Young",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "27 Sep 2024, 05:10 PM",
    resources: [
      "Backend Development",
      "Testing",
      "Project Management",
      "UX/UI Design",
    ],
    start_date: "03 Apr 2024",
    end_date: "28 Jan 2024",
    estimated_cost: 13765,
  },
  {
    id: "23",
    name: "Titan web app",
    project_manager: "Henry Clark",
    status: STATUS.RISK,
    last_updated: "13 May 2024, 07:45 AM",
    resources: [
      "Project Management",
      "Marketing",
      "Frontend Development",
      "QA",
    ],
    start_date: "08 Jan 2024",
    end_date: "18 Mar 2024",
    estimated_cost: 15632,
  },
  {
    id: "24",
    name: "Ocean web app",
    project_manager: "Elijah Wright",
    status: STATUS.ON_HOLD,
    last_updated: "19 Nov 2024, 12:14 PM",
    resources: ["Frontend Development", "Data Analysis", "Infrastructure"],
    start_date: "15 Feb 2024",
    end_date: "22 Jul 2024",
    estimated_cost: 12345,
  },
  {
    id: "25",
    name: "Sun web app",
    project_manager: "Mason Lee",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "01 Sep 2024, 11:01 AM",
    resources: ["QA", "Backend Development", "Research & Development"],
    start_date: "12 May 2024",
    end_date: "06 Dec 2024",
    estimated_cost: 12456,
  },
  {
    id: "26",
    name: "Cosmos web app",
    project_manager: "James Lee",
    status: STATUS.RISK,
    last_updated: "05 Aug 2024, 03:12 PM",
    resources: [
      "Marketing",
      "Backend Development",
      "Frontend Development",
      "Project Management",
    ],
    start_date: "29 Mar 2024",
    end_date: "21 Dec 2024",
    estimated_cost: 14234,
  },
  {
    id: "27",
    name: "Matrix web app",
    project_manager: "Charlotte Harris",
    status: STATUS.ON_TRACK,
    last_updated: "11 Nov 2024, 09:45 AM",
    resources: ["Research & Development", "Project Management", "QA"],
    start_date: "19 Mar 2024",
    end_date: "30 Oct 2024",
    estimated_cost: 11987,
  },
  {
    id: "28",
    name: "Phoenix web app",
    project_manager: "Liam Martin",
    status: STATUS.ON_HOLD,
    last_updated: "17 Dec 2024, 04:34 AM",
    resources: [
      "Data Analysis",
      "Frontend Development",
      "Infrastructure",
      "Project Management",
    ],
    start_date: "09 Apr 2024",
    end_date: "22 Feb 2024",
    estimated_cost: 9732,
  },
  {
    id: "29",
    name: "Nova web app",
    project_manager: "Emma Taylor",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "16 May 2024, 08:15 AM",
    resources: ["Testing", "Research & Development", "Frontend Development"],
    start_date: "24 Jan 2024",
    end_date: "27 Oct 2024",
    estimated_cost: 13243,
  },
  {
    id: "30",
    name: "Apollo web app",
    project_manager: "Aiden Clark",
    status: STATUS.ON_TRACK,
    last_updated: "30 Jul 2024, 12:50 PM",
    resources: [
      "Frontend Development",
      "Backend Development",
      "Project Management",
      "Testing",
    ],
    start_date: "10 Jun 2024",
    end_date: "19 Jan 2024",
    estimated_cost: 14278,
  },
  {
    id: "31",
    name: "Quantum web app",
    project_manager: "Lucas Taylor",
    status: STATUS.ON_HOLD,
    last_updated: "06 Jul 2024, 02:04 PM",
    resources: ["Backend Development", "Marketing", "Research & Development"],
    start_date: "28 Apr 2024",
    end_date: "16 Feb 2024",
    estimated_cost: 11687,
  },
  {
    id: "32",
    name: "Star web app",
    project_manager: "Jack Robinson",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "18 Oct 2024, 07:45 AM",
    resources: [
      "Infrastructure",
      "Testing",
      "Frontend Development",
      "Data Analysis",
    ],
    start_date: "07 Mar 2024",
    end_date: "29 Oct 2024",
    estimated_cost: 13234,
  },
  {
    id: "33",
    name: "Solar web app",
    project_manager: "Amelia King",
    status: STATUS.ON_TRACK,
    last_updated: "14 Oct 2024, 09:10 PM",
    resources: ["Frontend Development", "Project Management", "Data Analysis"],
    start_date: "03 Jan 2024",
    end_date: "30 Mar 2024",
    estimated_cost: 14980,
  },
  {
    id: "34",
    name: "Sky web app",
    project_manager: "Charlotte Young",
    status: STATUS.ON_HOLD,
    last_updated: "25 Jul 2024, 05:45 AM",
    resources: ["UX/UI Design", "Testing", "Project Management", "Marketing"],
    start_date: "27 Apr 2024",
    end_date: "12 Jan 2024",
    estimated_cost: 11853,
  },
  {
    id: "35",
    name: "Mars web app",
    project_manager: "Oliver Green",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "21 Jun 2024, 10:20 AM",
    resources: [
      "Backend Development",
      "Frontend Development",
      "Data Analysis",
      "Research & Development",
    ],
    start_date: "14 Apr 2024",
    end_date: "08 Feb 2024",
    estimated_cost: 15432,
  },
  {
    id: "36",
    name: "Venus web app",
    project_manager: "Mia Anderson",
    status: STATUS.RISK,
    last_updated: "28 Jan 2024, 01:50 AM",
    resources: [
      "QA",
      "Frontend Development",
      "Project Management",
      "Marketing",
    ],
    start_date: "19 Feb 2024",
    end_date: "26 Dec 2024",
    estimated_cost: 10239,
  },
  {
    id: "37",
    name: "Neptune web app",
    project_manager: "Zoe Carter",
    status: STATUS.ON_HOLD,
    last_updated: "23 Oct 2024, 03:15 AM",
    resources: ["Backend Development", "Marketing", "Project Management"],
    start_date: "09 Feb 2024",
    end_date: "25 Jun 2024",
    estimated_cost: 9465,
  },
  {
    id: "38",
    name: "Jupiter web app",
    project_manager: "Samuel Bell",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "09 Sep 2024, 07:10 PM",
    resources: [
      "Project Management",
      "Backend Development",
      "Frontend Development",
    ],
    start_date: "18 May 2024",
    end_date: "07 Dec 2024",
    estimated_cost: 12367,
  },
  {
    id: "39",
    name: "Pluto web app",
    project_manager: "Grace Scott",
    status: STATUS.RISK,
    last_updated: "15 Jul 2024, 11:12 PM",
    resources: [
      "UX/UI Design",
      "Data Analysis",
      "Testing",
      "Frontend Development",
    ],
    start_date: "06 Apr 2024",
    end_date: "11 Mar 2024",
    estimated_cost: 11634,
  },
  {
    id: "40",
    name: "Eclipse web app",
    project_manager: "Joshua Martin",
    status: STATUS.ON_TRACK,
    last_updated: "27 Sep 2024, 08:25 PM",
    resources: ["Testing", "Project Management", "Backend Development"],
    start_date: "12 Feb 2024",
    end_date: "17 Dec 2024",
    estimated_cost: 10560,
  },
  {
    id: "41",
    name: "Meteor web app",
    project_manager: "Lily King",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "06 Dec 2024, 10:13 PM",
    resources: [
      "Infrastructure",
      "Data Analysis",
      "Project Management",
      "Frontend Development",
    ],
    start_date: "22 Mar 2024",
    end_date: "20 Nov 2024",
    estimated_cost: 12745,
  },
  {
    id: "42",
    name: "Planet web app",
    project_manager: "Benjamin Lewis",
    status: STATUS.RISK,
    last_updated: "15 May 2024, 01:43 PM",
    resources: ["Marketing", "Project Management", "Frontend Development"],
    start_date: "04 Oct 2024",
    end_date: "16 Feb 2024",
    estimated_cost: 9932,
  },
  {
    id: "43",
    name: "Sunset web app",
    project_manager: "Chloe Johnson",
    status: STATUS.ON_HOLD,
    last_updated: "02 Oct 2024, 02:30 PM",
    resources: [
      "Backend Development",
      "Frontend Development",
      "Research & Development",
    ],
    start_date: "14 Mar 2024",
    end_date: "02 Dec 2024",
    estimated_cost: 11944,
  },
  {
    id: "44",
    name: "Light web app",
    project_manager: "Oliver Harris",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "21 Apr 2024, 04:03 PM",
    resources: [
      "Data Analysis",
      "Testing",
      "Frontend Development",
      "Project Management",
    ],
    start_date: "23 May 2024",
    end_date: "08 Sep 2024",
    estimated_cost: 10432,
  },
  {
    id: "45",
    name: "Starship web app",
    project_manager: "Harper Wilson",
    status: STATUS.RISK,
    last_updated: "26 May 2024, 12:14 AM",
    resources: ["Testing", "Backend Development", "Project Management"],
    start_date: "18 Nov 2024",
    end_date: "21 Jan 2024",
    estimated_cost: 13890,
  },
  {
    id: "46",
    name: "Echo web app",
    project_manager: "Jackie Thomas",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "15 Nov 2024, 01:20 AM",
    resources: [
      "Project Management",
      "Frontend Development",
      "Backend Development",
      "Research & Development",
    ],
    start_date: "13 Dec 2024",
    end_date: "10 Apr 2024",
    estimated_cost: 14870,
  },
  {
    id: "47",
    name: "Cloud web app",
    project_manager: "Ruby Green",
    status: STATUS.ON_HOLD,
    last_updated: "30 Jul 2024, 03:50 PM",
    resources: ["Marketing", "Project Management", "Infrastructure"],
    start_date: "19 Jan 2024",
    end_date: "29 Aug 2024",
    estimated_cost: 12367,
  },
  {
    id: "48",
    name: "Solaris web app",
    project_manager: "Matthew Bell",
    status: STATUS.RISK,
    last_updated: "08 Dec 2024, 07:15 AM",
    resources: ["Frontend Development", "Backend Development"],
    start_date: "25 Mar 2024",
    end_date: "22 May 2024",
    estimated_cost: 14870,
  },
  {
    id: "49",
    name: "Nova web app",
    project_manager: "Caden Wilson",
    status: STATUS.ON_TRACK,
    last_updated: "10 Feb 2024, 05:10 PM",
    resources: [
      "Testing",
      "Project Management",
      "Backend Development",
      "Frontend Development",
    ],
    start_date: "17 Jan 2024",
    end_date: "04 Aug 2024",
    estimated_cost: 15642,
  },
  {
    id: "50",
    name: "Matrix web app",
    project_manager: "Ella Young",
    status: STATUS.POTENTIAL_RISK,
    last_updated: "23 Nov 2024, 12:36 AM",
    resources: [
      "Frontend Development",
      "Backend Development",
      "Data Analysis",
      "QA",
    ],
    start_date: "14 Feb 2024",
    end_date: "20 Oct 2024",
    estimated_cost: 13972,
  },
];
